language: node_js
node_js: node
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - ghostscript
before_deploy:
  - echo "$gpg_key" | gpg --batch --passphrase-fd 0 .travis/deploy_key.gpg
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key
  - ssh-add .travis/deploy_key
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|release-.*)$
